services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5679:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secret
    volumes:
      - ./n8n_data:/home/node/.n8n

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - n8n
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app